aws:
  region: eu-west-1
  availability_zone_a: eu-west-1a
  availability_zone_b: eu-west-1b
  availability_zone_c: eu-west-1c

proxy:
  enabled: false
  protocol:
  host:
  port:

cron:
  env_path: /sbin:/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin
  https_proxy:

stack_manager_sns_topic_arn:
