stack_prefix: default

roles:
  stack_name: aem-roles-stack
  publish_dispatcher: AEMStackPublishDispatcherRole
  publish: AEMStackPublishRole
  author: AEMStackAuthorRole
  author_dispatcher: AEMStackAuthorDispatcherRole
  orchestrator: AEMStackOrchestratorRole
  chaos_monkey: AEMStackChaosMonkeyRole

ami_ids:
  author: ami-1ec5c17d
  publish: ami-f0ccc893
  author_dispatcher: ami-20c1c543
  publish_dispatcher: ami-20c1c543
  orchestrator: ami-e3c4c080
  chaos_monkey: ami-e3c4c080

security_groups:
  stack_name: aem-security-groups-stack
  secure_shell:
    inbound_cidr_ip: 10.0.10.0/25

  private_subnet_internet_outbound_cidr_ip: 0.0.0.0/0

  publish_dispatcher_elb:
    tag_name: AEM Publish Dispatcher ELB Security Group
    inbound_cidr_ip: 10.0.10.0/25

  publish_dispatcher:
    tag_name: AEM Publish Dispatcher Security Group

  publish:
    tag_name: AEM Publish Security Group

  author:
    tag_name: AEM Author Security Group

  author_elb:
    tag_name: AEM Author ELB Security Group

  author_dispatcher:
    tag_name: AEM Author Dispatcher Security Group

  author_dispatcher_elb:
    tag_name: AEM Author Dispatcher ELB Security Group
    inbound_cidr_ip: 10.0.10.0/25

  orchestrator:
    tag_name: AEM Orchestrator Security Group

  chaos_monkey:
    tag_name: AEM Chaos Monkey Security Group

messaging:
  stack_name: aem-messaging-stack
  asg_event_sqs_queue_name: aem-asg-event-queue
  asg_event_sns_topic_name: aem-asg-event-topic
  asg_event_sns_topic_display_name: AEM ASG Event Topic

route53:
  hosted_zone_name: aem-stack.com.

compute:
  key_pair_name: aem-stack-key-pair
  application_version: 1.0.0
  certificate_name: aem-stack-certificate
  inbound_from_bastion_host_security_group: sg-a5ac6cc2
  init_script_s3_uri: s3://aem-stack-builder/init.sh

publish_dispatcher:
  stack_name: aem-publish-dispatcher-stack
  instance_profile: aem-roles-stack-PublishDispatcherInstanceProfile-FSFBXO7Q2ESY
  instance_type: t2.micro
  min_size: 2
  max_size: 2
  load_balancer:
    tag_name: AEM Publish Dispatcher Load Balancer
  tag_name: AEM Publish Dispatcher
  elb_health_check: HTTP:80/system/health?tags=devops
  route53_record_set_name: publish-dispatcher.aem-stack.com.

publish:
  stack_name: aem-publish-stack
  instance_profile: aem-roles-stack-PublishInstanceProfile-MHV78N8CCU6O
  instance_type: m3.large
  min_size: 2
  max_size: 2
  tag_name: AEM Publish

author:
  stack_name: aem-author-stack
  instance_profile: aem-roles-stack-AuthorInstanceProfile-OYGRS9FHB0L9
  instance_type: m3.large
  load_balancer:
    tag_name: AEM Author Load Balancer
  tag_name: AEM Author
  elb_health_check: HTTP:4502/system/health?tags=devops
  route53_record_set_name: author.aem-stack.com.

author_dispatcher:
  stack_name: aem-author-dispatcher-stack
  instance_profile: aem-roles-stack-AuthorDispatcherInstanceProfile-1Q5WZ99PPURIY
  instance_type: t2.micro
  min_size: 2
  max_size: 2
  load_balancer:
    tag_name: AEM Author Dispatcher Load Balancer
  tag_name: AEM Author Dispatcher
  elb_health_check: HTTP:80/system/health?tags=devops
  route53_record_set_name: author-dispatcher.aem-stack.com.

orchestrator:
  stack_name: aem-orchestrator-stack
  instance_profile: aem-roles-stack-OrchestratorInstanceProfile-1VWFVJ2JNUY3S
  instance_type: t2.small
  tag_name: AEM Orchestrator

chaos_monkey:
  stack_name: aem-chaos-monkey-stack
  instance_profile: aem-roles-stack-ChaosMonkeyInstanceProfile-1C63DS268SWHK
  instance_type: t2.micro
  tag_name: AEM Chaos Monkey
