---

aem_vpc:
  id: vpc-2fc3014b
  author_dispatcher_subnet_a_id: subnet-8562f4e1
  author_dispatcher_subnet_b_id: subnet-0e2f9178
  author_subnet_a_id: subnet-8462f4e0
  author_subnet_b_id: subnet-022f9174
  chaos_monkey_subnet_a_id: subnet-8662f4e2
  chaos_monkey_subnet_b_id: subnet-052f9173
  orchestrator_subnet_a_id: subnet-8662f4e2
  orchestrator_subnet_b_id: subnet-052f9173
  publish_dispatcher_elb_subnet_a_id: subnet-8162f4e5
  publish_dispatcher_elb_subnet_b_id: subnet-002f9176
  publish_dispatcher_subnet_a_id: subnet-8762f4e3
  publish_dispatcher_subnet_b_id: subnet-012f9177
  publish_subnet_a_id: subnet-8062f4e4
  publish_subnet_b_id: subnet-032f9175

roles:
  stack_name: aem-roles-stack
  publish_dispatcher: AEMStackPublishDispatcherRole
  publish: AEMStackPublishRole
  author: AEMStackAuthorRole
  author_dispatcher: AEMStackAuthorDispatcherRole
  orchestrator: AEMStackOrchestratorRole
  chaos_monkey: AEMStackChaosMonkeyRole

ami_ids:
  author: ami-e12a2c82
  publish: ami-d6080eb5
  author_dispatcher: ami-c3282ea0
  publish_dispatcher: ami-c3282ea0
  orchestrator: ami-4c2b2d2f
  chaos_monkey: ami-4c2b2d2f

security_groups:
  stack_name: aem-security-groups-stack
  secure_shell:
    inbound_cidr_ip: 10.0.10.0/25

  private_subnet_internet_outbound_cidr_ip: 0.0.0.0/0

  publish_dispatcher_elb:
    tag_name: AEM Publish Dispatcher ELB Security Group
    inbound_cidr_ip: 10.0.10.0/25

  publish_dispatcher:
    tag_name: AEM Publish Dispatcher Security Group

  publish:
    tag_name: AEM Publish Security Group

  author:
    tag_name: AEM Author Security Group

  author_elb:
    tag_name: AEM Author ELB Security Group

  author_dispatcher:
    tag_name: AEM Author Dispatcher Security Group

  author_dispatcher_elb:
    tag_name: AEM Author Dispatcher ELB Security Group
    inbound_cidr_ip: 10.0.10.0/25

  orchestrator:
    tag_name: AEM Orchestrator Security Group

  chaos_monkey:
    tag_name: AEM Chaos Monkey Security Group

messaging:
  stack_name: aem-messaging-stack
  asg_event_sqs_queue_name: aem-asg-event-queue
  asg_event_sns_topic_name: aem-asg-event-topic
  asg_event_sns_topic_display_name: AEM ASG Event Topic

compute:
  key_pair_name: cliffs-sandpit
  application_version: 1.0.0
  certificate_name: aem-stack-certificate
  inbound_from_bastion_host_security_group: sg-a5ac6cc2

s3:
  data_bucket_name: aem-stack-builder

publish_dispatcher:
  stack_name: aem-publish-dispatcher-stack
  instance_profile: cliffs-aem-roles-stack-PublishInstanceProfile-DNZJ49E17ZK4
  instance_type: t2.micro
  min_size: 2
  max_size: 2
  load_balancer:
    tag_name: AEM Publish Dispatcher Load Balancer
  tag_name: AEM Publish Dispatcher
  elb_health_check: HTTP:80/system/health?tags=devops
  elb_scheme: internet-facing

publish:
  stack_name: aem-publish-stack
  instance_profile: cliffs-aem-roles-stack-PublishDispatcherInstanceProfile-121ECAZK2TPY0
  instance_type: m3.large
  min_size: 2
  max_size: 2
  tag_name: AEM Publish

author:
  stack_name: aem-author-stack
  instance_profile: cliffs-aem-roles-stack-AuthorInstanceProfile-1KIV5LHVC4WF3
  instance_type: m3.large
  load_balancer:
    tag_name: AEM Author Load Balancer
  tag_name: AEM Author
  elb_health_check: HTTP:4502/system/health?tags=devops

author_dispatcher:
  stack_name: aem-author-dispatcher-stack
  instance_profile: cliffs-aem-roles-stack-AuthorDispatcherInstanceProfile-1185QRCTDDPQ
  instance_type: t2.micro
  min_size: 2
  max_size: 2
  load_balancer:
    tag_name: AEM Author Dispatcher Load Balancer
  tag_name: AEM Author Dispatcher
  elb_health_check: HTTP:80/system/health?tags=devops

orchestrator:
  stack_name: aem-orchestrator-stack
  instance_profile: cliffs-aem-roles-stack-OrchestratorInstanceProfile-N42J44423JGR
  instance_type: t2.small
  tag_name: AEM Orchestrator

chaos_monkey:
  stack_name: aem-chaos-monkey-stack
  instance_profile: cliffs-aem-roles-stack-ChaosMonkeyInstanceProfile-901SCI66LQGO
  instance_type: t2.micro
  tag_name: AEM Chaos Monkey

dns_records:
  stack_name: aem-dns-records
  route53_hosted_zone_name: aem-stack.com.
  author:
    record_set_name: author
  author_dispatcher:
    record_set_name: author-dispatcher
  publish_dispatcher:
    record_set_name: publish-dispatcher
