---

aem_vpc:
  id: change-me
  author_dispatcher_subnet_a_id: change-me
  author_dispatcher_subnet_b_id: change-me
  author_subnet_a_id: change-me
  author_subnet_b_id: change-me
  chaos_monkey_subnet_a_id: change-me
  chaos_monkey_subnet_b_id: change-me
  orchestrator_subnet_a_id: change-me
  orchestrator_subnet_b_id: change-me
  publish_dispatcher_elb_subnet_a_id: change-me
  publish_dispatcher_elb_subnet_b_id: change-me
  publish_dispatcher_subnet_a_id: change-me
  publish_dispatcher_subnet_b_id: change-me
  publish_subnet_a_id: change-me
  publish_subnet_b_id: change-me
  author_publish_dispatcher_subnet_id: change-me

aem:
  enable_crxde: false
  enable_default_passwords: false

roles:
  stack_name: aem-roles-stack
  publish_dispatcher: AEMStackPublishDispatcherRole
  publish: AEMStackPublishRole
  author: AEMStackAuthorRole
  author_dispatcher: AEMStackAuthorDispatcherRole
  orchestrator: AEMStackOrchestratorRole
  chaos_monkey: AEMStackChaosMonkeyRole

ami_ids:
  author: change-me
  publish: change-me
  author_dispatcher: change-me
  publish_dispatcher: change-me
  author_publish_dispatcher: change-me
  orchestrator: change-me
  chaos_monkey: change-me

ami_root_device_name: /dev/sda1

security_groups:
  stack_name: aem-security-groups-stack
  secure_shell:
    inbound_cidr_ip: change-me

  private_subnet_internet_outbound_cidr_ip: 0.0.0.0/0

  publish_dispatcher_elb:
    tag_name: AEM Publish Dispatcher ELB Security Group
    inbound_cidr_ip: change-me

  publish_dispatcher:
    tag_name: AEM Publish Dispatcher Security Group

  publish:
    tag_name: AEM Publish Security Group

  author:
    tag_name: AEM Author Security Group

  author_elb:
    tag_name: AEM Author ELB Security Group

  author_dispatcher:
    tag_name: AEM Author Dispatcher Security Group

  author_dispatcher_elb:
    tag_name: AEM Author Dispatcher ELB Security Group
    inbound_cidr_ip: change-me

  orchestrator:
    tag_name: AEM Orchestrator Security Group

  chaos_monkey:
    tag_name: AEM Chaos Monkey Security Group

messaging:
  stack_name: aem-messaging-stack
  asg_event_sqs_queue_name: aem-asg-event-queue
  asg_event_sns_topic_name: aem-asg-event-topic
  asg_event_sns_topic_display_name: AEM ASG Event Topic
  alarm_notification:
    topic_name: alarm-notification-topic
    contact_email: change-me

compute:
  key_pair_name: change-me
  inbound_from_bastion_host_security_group: change-me

s3:
  data_bucket_name: aem-stack-builder

library:
  aem_aws_stack_provisioner_version: 0.9.0
  aem_orchestrator_version: 1.0.0
  aem_password_reset_version: 1.0.1
  oak_run_version: 1.4.15

publish_dispatcher:
  stack_name: aem-publish-dispatcher-stack
  instance_profile: change-me
  instance_type: t2.micro
  min_size: 2
  desired_capacity: 2
  max_size: 2
  root_vol_size: 20
  data_vol_size: 20
  load_balancer:
    tag_name: AEM Publish Dispatcher Load Balancer
  tag_name: AEM Publish Dispatcher
  elb_health_check: HTTPS:443/system/health?tags=shallow
  elb_scheme: internet-facing
  allowed_client: '*.*.*.*'
  certificate_name: aem-stack-builder

publish:
  stack_name: aem-publish-stack
  instance_profile: change-me
  instance_type: m3.large
  min_size: 2
  desired_capacity: 2
  max_size: 2
  root_vol_size: 20
  data_vol_size: 50
  tag_name: AEM Publish

author:
  stack_name: aem-author-stack
  instance_profile: change-me
  instance_type: m3.large
  root_vol_size: 20
  data_vol_size: 50
  load_balancer:
    tag_name: AEM Author Load Balancer
  tag_name: AEM Author
  elb_health_check: HTTPS:5433/system/health?tags=shallow
  certificate_name: change-me

snapshots:
  author:
    use_data_vol_snapshot: 'false'
    data_vol_snapshot_id: change-me
  publish:
    use_data_vol_snapshot: 'false'
    data_vol_snapshot_id: change-me

author_dispatcher:
  stack_name: aem-author-dispatcher-stack
  instance_profile: change-me
  instance_type: t2.micro
  min_size: 0
  desired_capacity: 2
  max_size: 2
  root_vol_size: 20
  data_vol_size: 20
  load_balancer:
    tag_name: AEM Author Dispatcher Load Balancer
  tag_name: AEM Author Dispatcher
  elb_health_check: HTTPS:443/system/health?tags=shallow
  certificate_name: aem-stack-builder

author_publish_dispatcher:
  stack_name: aem-author-publish-dispatcher-stack
  instance_type: m4.xlarge
  root_vol_size: 20
  data_vol_size: 20
  tag_name: AEM Author Publish Dispatcher
  associate_public_ip_address: true
  security_group: change-me

orchestrator:
  stack_name: aem-orchestrator-stack
  instance_profile: change-me
  instance_type: t2.small
  root_vol_size: 20
  data_vol_size: 20
  tag_name: AEM Orchestrator

chaos_monkey:
  stack_name: aem-chaos-monkey-stack
  instance_profile: change-me
  instance_type: t2.micro
  root_vol_size: 20
  tag_name: AEM Chaos Monkey

dns_records:
  stack_name: aem-dns-records
  route53_hosted_zone_name: change-me.com.
  author:
    record_set_name: author
  author_dispatcher:
    record_set_name: author-dispatcher
  publish_dispatcher:
    record_set_name: publish-dispatcher
  author_publish_dispatcher:
    record_set_name: author-publish-dispatcher
    ttl: 300
