---
AWSTemplateFormatVersion: "2010-09-09"

Description: Create the Compute resources for the AEM Author Publish Dispatcher

Parameters:

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix
    Default: "sshim"

  AuthorPublishDispatcherImageId:
    Type: AWS::EC2::Image::Id
    Description: AMI Id used for the Host
    Default: "ami-e2997f80"

  AuthorPublishDispatcherKeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key Pair Name
    Default: "sshim-sandpit"

  AuthorPublishDispatcherSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet Ids the Host Will be Launched into
    Default: "subnet-7d0bf80a"

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC that the Host will reside
    Default: "vpc-b3ad53d6"

Resources:

  # AuthorPublishDispatcher Security Group
  AuthorPublishDispatcherSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: AuthorPublishDispatcher Security Group
      Tags:
        - Key: Name
          Value: AuthorPublishDispatcher Security Group
      VpcId:
        Ref: VPCId

  # Allow tcp on ports 22
  AuthorPublishDispatcherSecurityGroupIngress0:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: '0.0.0.0/0'
      FromPort: '22'
      GroupId:
        Ref: AuthorPublishDispatcherSecurityGroup
      IpProtocol: tcp
      ToPort: '22'

  # Allow tcp on ports 4502, 4503
  AuthorPublishDispatcherSecurityGroupIngress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: '0.0.0.0/0'
      FromPort: '4502'
      GroupId:
        Ref: AuthorPublishDispatcherSecurityGroup
      IpProtocol: tcp
      ToPort: '4503'

  # Allow tcp on ports 5432, 5433
  AuthorPublishDispatcherSecurityGroupIngress2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: '0.0.0.0/0'
      FromPort: '5432'
      GroupId:
        Ref: AuthorPublishDispatcherSecurityGroup
      IpProtocol: tcp
      ToPort: '5433'


  AuthorPublishDispatcherRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
        - PolicyName: AuthorPublishDispatcherRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - ec2:AttachVolume
                  - ec2:CreateVolume
                  - ec2:DetachVolume
                  - ec2:CreateSnapshot
                  - ec2:CreateTags
                  - ec2:ModifyInstanceAttribute
                  - cloudwatch:PutMetricData
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Put*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*
      RoleName: AuthorPublishDispatcherStackPublishRole

  AuthorPublishDispatcherInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: AuthorPublishDispatcherRole


  AuthorPublishDispatcher:
    Type: "AWS::EC2::Instance"
    Properties:
      IamInstanceProfile:
        Ref: AuthorPublishDispatcherInstanceProfile
      ImageId:
        Ref: AuthorPublishDispatcherImageId
      InstanceType: m4.large
      KeyName:
        Ref: AuthorPublishDispatcherKeyPairName
      NetworkInterfaces:
        -
          AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - Ref: AuthorPublishDispatcherSecurityGroup
          SubnetId:
            Ref: AuthorPublishDispatcherSubnet
      Tags:
        - Key: Name
          Value: AuthorPublishDispatcher
        - Key: Component
          Value: author-primary
        - Key: StackPrefix
          Value:
            Ref: ComputeStackPrefixParameter
