---
AWSTemplateFormatVersion: "2010-09-09"

Description: Create the Compute resources for the AEM Author Publish Dispatcher

Parameters:

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  AuthorPublishDispatcherImageParameter:
    Type: AWS::EC2::Image::Id
    Description: AMI Id used for the Host

  AuthorPublishDispatcherImageRootDevice:
    Type: String
    Description: The root device name for the Author Publish Dispatcher Image Id
    Default: /dev/sda1

  AuthorPublishDispatcherInstanceTypeParameter:
    Type: String
    Description: The Author Publish Dispatcher Instance Type

  AuthorPublishDispatcherInstanceProfilePre:
    Type: String
    Description: The Author Publish Dispatcher pre-created Instance Profile
    Default: NONE

  AuthorPublishDispatcherDefaultSecurityGroupParameter:
    Type: String
    Description: The Author Publish Dispatcher default Security Group ID

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  AuthorPublishDispatcherRootVolSizeParameter:
    Type: Number
    Description: Author Publish Dispatcher Instances Root EBS Volume Size

  AuthorPublishDispatcherDataVolSizeParameter:
    Type: Number
    Description: Author Publish Dispatcher Instances Data EBS Volume Size

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC that the Host will reside

  AuthorPublishDispatcherSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet Ids the Host Will be Launched into

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

  AssociatePublicIpAddressParameter:
    Type: String
    Description: Add Public IP Address to instance

  Route53HostedZoneNameParameter:
    Type: String
    Description: Route53 Hosted Zone Name the Record Set will be Created in

  AuthorPublishDispatcherDNSRecordSetNameParameter:
    Type: String
    Description: Author DNS Record Set Name

  DNSRecordSetTTL:
    Type: String
    Description: Record Set TTL value

Conditions:

  createNewInstanceProfile: !Equals [!Ref AuthorPublishDispatcherInstanceProfilePre, NONE]

Resources:

  AuthorPublishDispatcherRole:
    Type: AWS::IAM::Role
    Condition: createNewInstanceProfile
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
        - PolicyName: AuthorPublishDispatcherRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - ec2:AttachVolume
                  - ec2:CreateVolume
                  - ec2:DetachVolume
                  - ec2:CreateSnapshot
                  - ec2:CreateTags
                  - ec2:ModifyInstanceAttribute
                  - cloudwatch:PutMetricData
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Put*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - arn:aws:logs:*:*:*
      RoleName: !Sub ${ComputeStackPrefixParameter}-AuthorPublishDispatcherStackPublishRole

  AuthorPublishDispatcherInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Condition: createNewInstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: AuthorPublishDispatcherRole

  AuthorPublishDispatcher:
    Type: "AWS::EC2::Instance"
    Properties:
      BlockDeviceMappings:
      - DeviceName: !Ref AuthorPublishDispatcherImageRootDevice
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorPublishDispatcherRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorPublishDispatcherDataVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdc
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorPublishDispatcherDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        !If [createNewInstanceProfile, !Ref AuthorPublishDispatcherInstanceProfile, !Ref AuthorPublishDispatcherInstanceProfilePre]
      ImageId:
        Ref: AuthorPublishDispatcherImageParameter
      InstanceType:
        Ref: AuthorPublishDispatcherInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      NetworkInterfaces:
        -
          AssociatePublicIpAddress:
            Ref: AssociatePublicIpAddressParameter
          DeviceIndex: "0"
          GroupSet:
            - Ref: AuthorPublishDispatcherDefaultSecurityGroupParameter
          SubnetId:
            Ref: AuthorPublishDispatcherSubnet
      Tags:
        - Key: StackPrefix
          Value:
            Ref: ComputeStackPrefixParameter
        - Key: Name
          Value: AuthorPublishDispatcher
        - Key: Component
          Value: author-publish-dispatcher
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n\
            \ source /etc/profile\n\
            \ mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${ComputeStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh ${DataBucketNameParameter} ${ComputeStackPrefixParameter} author-publish-dispatcher ${AemAwsStackProvisionerVersionParameter}\n"

  AuthorPublishDispatcherRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref Route53HostedZoneNameParameter
      Name:
        Fn::Sub: ${ComputeStackPrefixParameter}-${AuthorPublishDispatcherDNSRecordSetNameParameter}.${Route53HostedZoneNameParameter}
      ResourceRecords:
        - Fn::GetAtt: [ AuthorPublishDispatcher, PrivateIp ]
      TTL: !Ref DNSRecordSetTTL
      Type: A
