---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Create the Compute resources for the AEM Chaos Monkey

Parameters:

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  ChaosMonkeyImageParameter:
    Type: AWS::EC2::Image::Id
    Description: The Chaos Monkey Image Id

  ChaosMonkeyInstanceTypeParameter:
    Type: String
    Description: The Chaos Monkey Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  ChaosMonkeyASGAvailabilityZoneListParameter:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The Chaos Monkey Availability Zone List

  ChaosMonkeyASGSubnetListParameter:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The Chaos Monkey Subnets

  ChaosMonkeyTagNameParameter:
    Type: String
    Description: The Chaos Monkey Name Tag

  ApplicationVersionParameter:
    Type: String
    Description: The Application Version Number

  RolesStackNameParameter:
    Type: String
    Description: The AEM Roles Stack Name

  SecurityGroupsStackNameParameter:
    Type: String
    Description: The AEM Security Groups Stack Name

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  InitScriptS3UriParameter:
    Type: String
    Description: Initialization Script executed via the User Data

Resources:

  ChaosMonkeyLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 10
            VolumeType: gp2
# TODO: Can not import IAM Instance Profile as it may already exist/be provided. Need to passed in as config or retrieved using iam.py if possible.
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: ${RolesStackNameParameter}-ChaosMonkeyInstanceProfile
      ImageId:
        Ref: ChaosMonkeyImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: ChaosMonkeyInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
        - Fn::ImportValue: !Sub ${ComputeStackPrefixParameter}-${SecurityGroupsStackNameParameter}-ChaosMonkeySecurityGroup
        - Ref: InboundFromBastionHostSecurityGroupParameter
# TODO: Implement versioning for init.sh e.g. .../aem-stack-builder/init/${initVersion}/init-${initVersion}.sh
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -x
            mkdir /tmp/aem-stack-builder
            aws s3 cp ${InitScriptS3UriParameter} /tmp/aem-stack-builder/init.sh
            chmod 755 /tmp/aem-stack-builder/init.sh
            su - ec2-user -c "/tmp/aem-stack-builder/init.sh"

  ChaosMonkeyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Ref: ChaosMonkeyASGAvailabilityZoneListParameter
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: ChaosMonkeyLaunchConfiguration
      MaxSize: 1
      MinSize: 1
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${ChaosMonkeyTagNameParameter} (${ComputeStackPrefixParameter})
          PropagateAtLaunch: true
        - Key: Stack Prefix
          Value:
            Ref: ComputeStackPrefixParameter
          PropagateAtLaunch: true
        - Key: Component
          Value: aem-chaos-monkey
          PropagateAtLaunch: true
        - Key: Application Version
          Value:
            Ref: ApplicationVersionParameter
          PropagateAtLaunch: true
      VPCZoneIdentifier:
        Ref: ChaosMonkeyASGSubnetListParameter

Outputs:

  ChaosMonkeyLaunchConfiguration:
    Value:
      Ref: ChaosMonkeyLaunchConfiguration
    Description: The Chaos Monkey Launch Configuration

  ChaosMonkeyAutoScalingGroup:
    Value:
      Ref: ChaosMonkeyAutoScalingGroup
    Description: The Chaos Monkey Auto Scaling Group
