---
AWSTemplateFormatVersion: "2010-09-09"

Description:   Create DNS Record Set in Route53 for AEM App Stacks

Parameters:
  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  Route53HostedZoneNameParameter:
    Type: String
    Description: Route53 Hosted Zone Name the Record Set will be Created in

  AuthorDNSRecordSetNameParameter:
    Type: String
    Description: Author DNS Record Set Name

  AuthorDispatcherDNSRecordSetNameParameter:
    Type: String
    Description: AuthorDispatcher DNS Record Set Name

  PublishDispatcherDNSRecordSetNameParameter:
    Type: String
    Description: PublishDispatcher DNS Record Set Name

Resources:
  StackZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Sub Hosted Zone for ${ComputeStackPrefixParameter} Stacks
      Name: !Sub ${ComputeStackPrefixParameter}.aem.${Route53HostedZoneNameParameter}


  AuthorRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Ref: StackZone
      Name:
        Fn::Sub: ${AuthorDNSRecordSetNameParameter}.${ComputeStackPrefixParameter}.aem.${Route53HostedZoneNameParameter}
      ResourceRecords:
        - Fn::ImportValue:
            Fn::Sub : ${ComputeStackPrefixParameter}-AuthorLoadBalancerDNSName
      TTL: 300
      Type: CNAME

  AuthorDispatcherRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Ref: StackZone
      Name:
        Fn::Sub: ${AuthorDispatcherDNSRecordSetNameParameter}.${ComputeStackPrefixParameter}.aem.${Route53HostedZoneNameParameter}
      ResourceRecords:
        - Fn::ImportValue:
            Fn::Sub: ${ComputeStackPrefixParameter}-AuthorDispatcherLoadBalancerDNSName
      TTL: 300
      Type: CNAME

  PublishDispatcherRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName:
        Fn::Sub: ${ComputeStackPrefixParameter}.aem.${Route53HostedZoneNameParameter}
      Name:
        Fn::Sub: ${PublishDispatcherDNSRecordSetNameParameter}.${ComputeStackPrefixParameter}.aem.${Route53HostedZoneNameParameter}
      ResourceRecords:
        - Fn::ImportValue:
            Fn::Sub: ${ComputeStackPrefixParameter}-PublishDispatcherLoadBalancerDNSName
      TTL: 300
      Type: CNAME

Outputs:
  StackZoneId:
    Value: !Ref StackZone
    Description: AEM Stack Route53 Zone Id
    Export:
      Name: !Sub ${ComputeStackPrefixParameter}-StackZoneId
