---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Create the Compute resources for the AEM Orchestrator

Parameters:

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  OrchestratorInstanceProfileParameter:
    Type: String
    Description: The Orchestrator Instance Profile

  OrchestratorImageParameter:
    Type: AWS::EC2::Image::Id
    Description: The Orchestrator Image Id

  OrchestratorInstanceTypeParameter:
    Type: String
    Description: The Orchestrator Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  OrchestratorASGAvailabilityZoneListParameter:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The Orchestrator Availability Zone List

  OrchestratorASGSubnetListParameter:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The Orchestrator Subnets

  OrchestratorTagNameParameter:
    Type: String
    Description: The Orchestrator Name Tag

  ApplicationVersionParameter:
    Type: String
    Description: The Application Version Number

  RolesStackNameParameter:
    Type: String
    Description: The AEM Roles Stack Name

  SecurityGroupsStackNameParameter:
    Type: String
    Description: The AEM Security Groups Stack Name

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  InitScriptS3UriParameter:
    Type: String
    Description: Initialization Script executed via the User Data

Resources:

  OrchestratorLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 10
            VolumeType: gp2
        - DeviceName: /dev/sdb
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 10
            VolumeType: gp2
      IamInstanceProfile:
        Ref: OrchestratorInstanceProfileParameter
      ImageId:
        Ref: OrchestratorImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: OrchestratorInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
        - Fn::ImportValue: !Sub ${ComputeStackPrefixParameter}-${SecurityGroupsStackNameParameter}-OrchestratorSecurityGroup
        - Ref: InboundFromBastionHostSecurityGroupParameter
# TODO: Implement versioning for init.sh e.g. .../aem-stack-builder/init/${initVersion}/init-${initVersion}.sh
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -x
            mkdir /tmp/aem-stack-builder
            aws s3 cp ${InitScriptS3UriParameter} /tmp/aem-stack-builder/init.sh
            chmod 755 /tmp/aem-stack-builder/init.sh
            su - ec2-user -c "/tmp/aem-stack-builder/init.sh"


  OrchestratorAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Ref: OrchestratorASGAvailabilityZoneListParameter
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: OrchestratorLaunchConfiguration
      MaxSize: 1
      MinSize: 1
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${OrchestratorTagNameParameter} (${ComputeStackPrefixParameter})
          PropagateAtLaunch: true
        - Key: Stack Prefix
          Value:
            Ref: ComputeStackPrefixParameter
          PropagateAtLaunch: true
        - Key: Component
          Value: aem-orchestrator
          PropagateAtLaunch: true
        - Key: Application Version
          Value:
            Ref: ApplicationVersionParameter
          PropagateAtLaunch: true
      VPCZoneIdentifier:
        Ref: OrchestratorASGSubnetListParameter

Outputs:

  OrchestratorLaunchConfiguration:
    Value:
      Ref: OrchestratorLaunchConfiguration
    Description: The Orchestrator Launch Configuration

  OrchestratorAutoScalingGroup:
    Value:
      Ref: OrchestratorAutoScalingGroup
    Description: The Orchestrator Auto Scaling Group
