---
- name: AEM Orchestrator CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create AEM Orchestrator Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ orchestrator.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/orchestrator.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          OrchestratorInstanceProfileParameter: "{{ orchestrator.instance_profile }}"
          OrchestratorImageParameter: "{{ ami_ids.orchestrator }}"
          OrchestratorInstanceTypeParameter: "{{ orchestrator.instance_type }}"
          ComputeKeyPairNameParameter: "{{ compute.key_pair_name }}"
          OrchestratorASGAvailabilityZoneListParameter: "{{ aws.availability_zone_a }}, {{ aws.availability_zone_b }}"
          OrchestratorASGSubnetListParameter: "{{ aem_vpc.orchestrator_subnet_a_id }}, {{ aem_vpc.orchestrator_subnet_b_id }}"
          OrchestratorTagNameParameter: "{{ stack_prefix }}-{{ orchestrator.tag_name }}"
          ApplicationVersionParameter: "{{ compute.application_version }}"
          RolesStackNameParameter: "{{ roles.stack_name }}"
          SecurityGroupsStackNameParameter: "{{ security_groups.stack_name }}"
          InboundFromBastionHostSecurityGroupParameter: "{{ compute.inbound_from_bastion_host_security_group }}"
          InitScriptS3UriParameter: "{{ compute.init_script_s3_uri }}"
      tags:
      - create

    - name: Delete AEM Orchestrator Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ orchestrator.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      tags:
      - delete
