---
- name: AEM Publish Dispatcher CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Get AEM Stack IAM Server Certificate
      iam_server_certificate_facts:
        name: "{{ compute.certificate_name }}"
      register: aem_stack_certificate
      tags:
      - create

    - name: Create AEM Publish Dispatcher Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ publish_dispatcher.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/publish-dispatcher.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          SSLCertificateARNParameter: "{{ aem_stack_certificate.results[compute.certificate_name].arn }}"
          PublishDispatcherLoadBalancerHealthCheckTargetParameter: "{{ publish_dispatcher.elb_health_check }}"
          PublishDispatcherELBSubnetAParameter: "{{ aem_vpc.publish_dispatcher_elb_subnet_a_id }}"
          PublishDispatcherELBSubnetBParameter: "{{ aem_vpc.publish_dispatcher_elb_subnet_b_id }}"
          PublishDispatcherInstanceProfileParameter: "{{ publish_dispatcher.instance_profile }}"
          PublishDispatcherImageParameter: "{{ ami_ids.publish_dispatcher }}"
          PublishDispatcherInstanceTypeParameter: "{{ publish_dispatcher.instance_type }}"
          ComputeKeyPairNameParameter: "{{ compute.key_pair_name }}"
          PublishDispatcherASGAvailabilityZoneListParameter: "{{ aws.availability_zone_a }}, {{ aws.availability_zone_b }}"
          PublishDispatcherASGSubnetListParameter: "{{ aem_vpc.publish_dispatcher_subnet_a_id }}, {{ aem_vpc.publish_dispatcher_subnet_b_id}}"
          PublishDispatcherASGMaxSizeParameter: "{{ publish_dispatcher.max_size }}"
          PublishDispatcherASGMinSizeParameter: "{{ publish_dispatcher.min_size }}"
          PublishDispatcherTagNameParameter: "{{ stack_prefix }}-{{ publish_dispatcher.tag_name }}"
          ApplicationVersionParameter: "{{ compute.application_version }}"
          PublishDispatcherLoadBalancerTagNameParameter: "{{ stack_prefix }}-{{ publish_dispatcher.load_balancer.tag_name }}"
          RolesStackNameParameter: "{{ roles.stack_name }}"
          SecurityGroupsStackNameParameter: "{{ security_groups.stack_name }}"
          MessagingStackNameParameter: "{{ messaging.stack_name }}"
          InboundFromBastionHostSecurityGroupParameter: "{{ compute.inbound_from_bastion_host_security_group }}"
          InitScriptS3UriParameter: "{{ compute.init_script_s3_uri }}"
      tags:
      - create

    - name: Delete AEM Publish Dispatcher Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ publish_dispatcher.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      tags:
      - delete
