---
- name: AEM Publish CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create AEM Publish Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ publish.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/publish.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          PublishInstanceProfileParameter: "{{ publish.instance_profile }}"
          PublishImageParameter: "{{ ami_ids.publish }}"
          PublishInstanceTypeParameter: "{{ publish.instance_type }}"
          ComputeKeyPairNameParameter: "{{ compute.key_pair_name }}"
          PublishASGAvailabilityZoneListParameter: "{{ aws.availability_zone_a }}, {{ aws.availability_zone_b }}"
          PublishASGSubnetListParameter: "{{ aem_vpc.publish_subnet_a_id }}, {{ aem_vpc.publish_subnet_b_id }}"
          PublishASGMaxSizeParameter: "{{ publish.max_size }}"
          PublishASGMinSizeParameter: "{{ publish.min_size }}"
          PublishTagNameParameter: "{{ stack_prefix }}-{{ publish.tag_name }}"
          ApplicationVersionParameter: "{{ compute.application_version }}"
          RolesStackNameParameter: "{{ roles.stack_name }}"
          SecurityGroupsStackNameParameter: "{{ security_groups.stack_name }}"
          MessagingStackNameParameter: "{{ messaging.stack_name }}"
          InboundFromBastionHostSecurityGroupParameter: "{{ compute.inbound_from_bastion_host_security_group }}"
          InitScriptS3UriParameter: "{{ compute.init_script_s3_uri }}"
      tags:
      - create

    - name: Delete AEM Publish Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ publish.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      tags:
      - delete
