---
- name: AEM Security Groups CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create AEM Security Groups Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ security_groups.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../cloudformation/apps/security-groups.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          NetworkStackPrefixParameter: "{{ security_groups.network_stack_prefix }}"
          SecureShellInboundCidrIpParameter: "{{ security_groups.secure_shell.inbound_cidr_ip }}"
          PublishDispatcherELBSecurityGroupInboundCidrIpParameter: "{{ security_groups.publish_dispatcher_elb.inbound_cidr_ip }}"
          PublishDispatcherELBSecurityGroupTagNameParameter: "{{ stack_prefix }}-{{ security_groups.publish_dispatcher_elb.tag_name }}"
          PublishDispatcherSecurityGroupTagNameParameter: "{{ stack_prefix }}-{{ security_groups.publish_dispatcher.tag_name }}"
          PublishSecurityGroupTagNameParameter: "{{ stack_prefix }}-{{ security_groups.publish.tag_name }}"
          AuthorSecurityGroupTagNameParameter: "{{ stack_prefix }}-{{ security_groups.author.tag_name }}"
          AuthorELBSecurityGroupTagNameParameter: "{{ stack_prefix }}-{{ security_groups.author_elb.tag_name }}"
          AuthorDispatcherSecurityGroupTagNameParameter: "{{ stack_prefix }}-{{ security_groups.author_dispatcher.tag_name }}"
          AuthorDispatcherELBSecurityGroupTagNameParameter: "{{ stack_prefix }}-{{ security_groups.author_dispatcher_elb.tag_name }}"
          AuthorDispatcherELBSecurityGroupInboundCidrIpParameter: "{{ security_groups.author_dispatcher_elb.inbound_cidr_ip }}"
          OrchestratorSecurityGroupTagNameParameter: "{{ stack_prefix }}-{{ security_groups.orchestrator.tag_name }}"
          ChaosMonkeySecurityGroupTagNameParameter: "{{ stack_prefix }}-{{ security_groups.chaos_monkey.tag_name }}"
          PrivateSubnetInternetOutboundCidrIpParameter: "{{ security_groups.private_subnet_internet_outbound_cidr_ip }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ security_groups.stack_name }}" --query 'Stacks[].StackName'
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ security_groups.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Security Groups Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ security_groups.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
