---
- name: AEM Author CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Create random credentials for system users
      system_users_credentials:
      register: credentials
      tags:
      - create
