---
- name: Deploy AEM Stack Manager Lambda Implementation
  hosts: all
  gather_facts: no
  connection: local
  vars:
    stack_manager_tmp: ./stack_manager_deploy

  tasks:
    - name: Create A Deploy Directory for Lambda Bundle and Config File
      file:
        path: "{{ stack_manager_tmp }}"
        state: directory
        mode: 0755
      tags:
        - create

    - name: Zip AEM Stack Manager Lambda Implementation
      command: >
        zip "{{ stack_manager_tmp }}/aem-stack-manager.zip" "../../../lambda/aem_stack_manager.py"
      tags:
        - create

    - name: Zip AEM Offline Snapshot Lambda Implementation
      command: >
        zip "{{ stack_manager_tmp }}/aem-offline-snapshot.zip" "../../../lambda/aem_offline_snapshot.py"
      tags:
        - create

    - name: Upload Stack Manager Zip Archives to S3
      s3_sync:
        bucket: "{{ s3.data_bucket_name }}"
        key_prefix: "{{ stack_prefix }}"
        mode: push
        file_root: "{{ stack_manager_tmp }}"
      when: " ansible_version.full >= '2.3' "
      tags:
        - create

    - name: Upload Stack Manager Zip Archive and Config File to S3
      command: >
              aws s3 sync "{{ stack_manager_tmp }}"
                  s3://{{ s3.data_bucket_name }}/{{ stack_prefix }}
      when: " ansible_version.full  < '2.3' "
      tags:
        - create

    - name: >
        Create AEM Stack Manager/Offline Snapshot Lambda Function and Resources
      cloudformation:
        stack_name: "{{ stack_prefix }}-aem-stack-manager-cloud"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: false
        template: "../../../cloudformation/manage/aem-stack-manager-cloud.yaml"
        template_parameters:
          StackPrefix: "{{ stack_prefix }}"
          S3Bucket: "{{ s3.data_bucket_name }}"
          S3Prefix: " {{ stack_prefix }}"
      register: stack_info
      tags:
        - create

    - name: Update config.json template to the stack output
      shell:  >
        jq --arg sns "{{ stack_info.stack_outputs.BackupTopicArn}}" \
           --arg role "{{ stack_info.stack_outputs.SSMServiceRoleArn}}" \
           --arg bucket "{{ s3.data_bucket_name }}" \
           '."offline_snapshot"."sns-topic-arn"=$sns|."offline_snapshot"."ssm-service-role-arn"=$role|."offline_snapshot"."cmd-output-bucket"=$bucket' \
           ../../../lambda/config.json.template  >  "{{ stack_manager_tmp }}"/config.json
      tags:
       - create

    - name: Upload config.json to S3
      s3:
         bucket: "{{ s3.data_bucket_name }}"
         mode: put
         src: "{{ stack_manager_tmp }}/config.json"
         object: "{{ stack_prefix }}/config.json"
      tags:
       - create

    - name: Clean Up Deploy Folder After
      file:
        path: "{{ stack_manager_tmp }}"
        state: absent
      tags:
        - create

    - name: Check if a Stack Exists
      command: >
        aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-aem-stack-manager-cloud"
             --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-aem-stack-manager-cloud" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Stack Manager Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-aem-stack-manager-cloud"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
        - delete
