---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Create Nat Gateway and add to private Route Table for AEM Stack

Parameters:

  Ec2NatGatewayElasticIpAllocationIdParameter:
    Type: String
    Default: eipalloc-32711957
    Description: The EC2 Nat Gateway Elastic Ip Allocation Id

  PublishDispatcherELBSubnetAParameter:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-8162f4e5
    Description: The Publish Dispatcher ELB Subnet in Availability Zone A

  NetworkStackNameParameter:
    Type: String
    Default: aem-network-stack
    Description: The AEM Network Stack Name


Resources:

# TODO: need to reference or use GetAtt for the EIP AllocationId
  Ec2NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: eipalloc-32711957
      SubnetId:
        Ref: PublishDispatcherELBSubnetAParameter

  PrivateInternetGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: Ec2NatGateway
      RouteTableId:
        Fn::ImportValue: !Sub  ${NetworkStackNameParameter}-PrivateRouteTable

Outputs:

  Ec2NatGateway:
    Value:
      Ref: Ec2NatGateway
    Description: The Nat-Gatway for the AEM Stack
