---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Create Subnets, Internet Gateway, and Route Tables for AEM Stack

Parameters:
  StackPrefix:
    Type: String
    Description: Used to Namespace the Exported Resources
    Default: ""

  VpcIdParameter:
    Type: AWS::EC2::VPC::Id
    Default: vpc-2fc3014b
    Description: The VPC to create the AEM Network in.

  AvailabilityZoneAParameter:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-southeast-2a
    Description: Availability Zone A

  AvailabilityZoneBParameter:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-southeast-2b
    Description: Availability Zone B

  Ec2InternetGatewayTagNameParameter:
    Type: String
    Default: AEM VPC Internet Gateway
    Description: AEM VPC Internet Gateway Name

  PublishDispatcherELBSubnetACidrBlockParameter:
    Type: String
    Default: 10.0.10.0/25
    Description: AEM Publish Dispatcher ELB Subnet A Cidr Block

  PublishDispatcherELBSubnetATagNameParameter:
    Type: String
    Default: AEM Publish Dispatcher ELB Subnet A
    Description: AEM Publish Dispatcher ELB Subnet A Name

  PublishDispatcherELBSubnetBCidrBlockParameter:
    Type: String
    Default: 10.0.10.128/25
    Description: AEM Publish Dispatcher ELB Subnet B Cidr Block

  PublishDispatcherELBSubnetBTagNameParameter:
    Type: String
    Default: AEM Publish Dispatcher ELB Subnet B
    Description: AEM Publish Dispatcher ELB Subnet B Name


  PublishDispatcherSubnetACidrBlockParameter:
    Type: String
    Default: 10.0.11.0/25
    Description: AEM Publish Dispatcher Subnet A Cidr Block

  PublishDispatcherSubnetATagNameParameter:
    Type: String
    Default: AEM Publish Dispatcher Subnet A
    Description: AEM Publish Dispatcher Subnet A Name

  PublishDispatcherSubnetBCidrBlockParameter:
    Type: String
    Default: 10.0.11.128/25
    Description: AEM Publish Dispatcher Subnet B Cidr Block

  PublishDispatcherSubnetBTagNameParameter:
    Type: String
    Default: AEM Publish Dispatcher Subnet B
    Description: AEM Publish Dispatcher Subnet B Name


  PublishSubnetACidrBlockParameter:
    Type: String
    Default: 10.0.12.0/25
    Description: AEM Publish Subnet A Cidr Block

  PublishSubnetATagNameParameter:
    Type: String
    Default: AEM Publish Subnet A
    Description: AEM Publish Subnet A Name

  PublishSubnetBCidrBlockParameter:
    Type: String
    Default: 10.0.12.128/25
    Description: AEM Publish Subnet B Cidr Block

  PublishSubnetBTagNameParameter:
    Type: String
    Default: AEM Publish Subnet B
    Description: AEM Publish Subnet B Name


  AuthorSubnetACidrBlockParameter:
    Type: String
    Default: 10.0.13.0/25
    Description: AEM Author Subnet A Cidr Block

  AuthorSubnetATagNameParameter:
    Type: String
    Default: AEM Author Subnet A
    Description: AEM Author Subnet A Name

  AuthorSubnetBCidrBlockParameter:
    Type: String
    Default: 10.0.13.128/25
    Description: AEM Author Subnet B Cidr Block

  AuthorSubnetBTagNameParameter:
    Type: String
    Default: AEM Auhtor Subnet B
    Description: AEM Author Subnet B Name


  AuthorDispatcherSubnetACidrBlockParameter:
    Type: String
    Default: 10.0.14.0/25
    Description: AEM Author Dispatcher Subnet A Cidr Block

  AuthorDispatcherSubnetATagNameParameter:
    Type: String
    Default: AEM Author Dispatcher Subnet A
    Description: AEM Author Dispatcher Subnet A Name

  AuthorDispatcherSubnetBCidrBlockParameter:
    Type: String
    Default: 10.0.14.128/25
    Description: AEM Author Dispatcher Subnet B Cidr Block

  AuthorDispatcherSubnetBTagNameParameter:
    Type: String
    Default: AEM Author Dispatcher Subnet B
    Description: AEM Author Dispatcher Subnet B Name


  ToolSubnetACidrBlockParameter:
    Type: String
    Default: 10.0.15.0/25
    Description: Tool Subnet A Cidr Block

  ToolSubnetATagNameParameter:
    Type: String
    Default: AEM Tool Subnet A
    Description: AEM Tool Subnet A Name

  ToolSubnetBCidrBlockParameter:
    Type: String
    Default: 10.0.15.128/25
    Description: Tool Subnet B Cidr Block

  ToolSubnetBTagNameParameter:
    Type: String
    Default: AEM Tool Subnet B
    Description: AEM Tool Subnet B Name


  PublicRouteTableTagNameParameter:
    Type: String
    Default: AEM VPC Public Route Table
    Description: AEM VPC Public Route Table Name

  PrivateRouteTableTagNameParameter:
    Type: String
    Default: AEM VPC Private Route Table
    Description: AEM VPC Private Route Table Name


Resources:
  Ec2InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value:
            Ref: Ec2InternetGatewayTagNameParameter

# TODO: set/change the Main Route Table?

  Ec2VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: Ec2InternetGateway
      VpcId:
        Ref: VpcIdParameter


  PublishDispatcherELBSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZoneAParameter
      CidrBlock:
        Ref: PublishDispatcherELBSubnetACidrBlockParameter
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Ref: PublishDispatcherELBSubnetATagNameParameter
      VpcId:
        Ref: VpcIdParameter

  PublishDispatcherELBSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZoneBParameter
      CidrBlock:
        Ref: PublishDispatcherELBSubnetBCidrBlockParameter
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Ref: PublishDispatcherELBSubnetBTagNameParameter
      VpcId:
        Ref: VpcIdParameter

  PublishDispatcherSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZoneAParameter
      CidrBlock:
        Ref: PublishDispatcherSubnetACidrBlockParameter
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Ref: PublishDispatcherSubnetATagNameParameter
      VpcId:
        Ref: VpcIdParameter

  PublishDispatcherSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZoneBParameter
      CidrBlock:
        Ref: PublishDispatcherSubnetBCidrBlockParameter
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Ref: PublishDispatcherSubnetBTagNameParameter
      VpcId:
        Ref: VpcIdParameter

  PublishSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZoneAParameter
      CidrBlock:
        Ref: PublishSubnetACidrBlockParameter
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Ref: PublishSubnetATagNameParameter
      VpcId:
        Ref: VpcIdParameter

  PublishSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZoneBParameter
      CidrBlock:
        Ref: PublishSubnetBCidrBlockParameter
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Ref: PublishSubnetBTagNameParameter
      VpcId:
        Ref: VpcIdParameter

  AuthorSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZoneAParameter
      CidrBlock:
        Ref: AuthorSubnetACidrBlockParameter
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Ref: AuthorSubnetATagNameParameter
      VpcId:
        Ref: VpcIdParameter

  AuthorSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZoneBParameter
      CidrBlock:
        Ref: AuthorSubnetBCidrBlockParameter
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Ref: AuthorSubnetBTagNameParameter
      VpcId:
        Ref: VpcIdParameter

  AuthorDispatcherSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZoneAParameter
      CidrBlock:
        Ref: AuthorDispatcherSubnetACidrBlockParameter
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Ref: AuthorDispatcherSubnetATagNameParameter
      VpcId:
        Ref: VpcIdParameter

  AuthorDispatcherSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZoneBParameter
      CidrBlock:
        Ref: AuthorDispatcherSubnetBCidrBlockParameter
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Ref: AuthorDispatcherSubnetBTagNameParameter
      VpcId:
        Ref: VpcIdParameter

  ToolSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZoneAParameter
      CidrBlock:
        Ref: ToolSubnetACidrBlockParameter
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Ref: ToolSubnetATagNameParameter
      VpcId:
        Ref: VpcIdParameter

  ToolSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Ref: AvailabilityZoneBParameter
      CidrBlock:
        Ref: ToolSubnetBCidrBlockParameter
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value:
            Ref: ToolSubnetBTagNameParameter
      VpcId:
        Ref: VpcIdParameter

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VpcIdParameter
      Tags:
        - Key: Name
          Value:
            Ref: PublicRouteTableTagNameParameter
# TODO: the RouteTable Name Tag is not being set?

  PublicInternetGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: Ec2InternetGateway
      RouteTableId:
        Ref: PublicRouteTable
    DependsOn: Ec2VPCGatewayAttachment

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VpcIdParameter
      Tags:
        - Key: Name
          Value:
            Ref: PrivateRouteTableTagNameParameter
# TODO: the RouteTable Name Tag is not being set?

  PublishDispatcherELBSubnetAPublicRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublishDispatcherELBSubnetA

  PublishDispatcherELBSubnetBPublicRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublishDispatcherELBSubnetB

  PublishDispatcherSubnetAPrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: PublishDispatcherSubnetA

  PublishDispatcherSubnetBPrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: PublishDispatcherSubnetB

  PublishSubnetAPrivatecRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: PublishSubnetA

  PublishSubnetBPrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: PublishSubnetB

  AuthorSubnetAPrivatecRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: AuthorSubnetA

  AuthorSubnetBPrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: AuthorSubnetB

  AuthorDispatcherSubnetAPrivatecRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: AuthorDispatcherSubnetA

  AuthorDispatcherSubnetBPrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: AuthorDispatcherSubnetB

  ToolSubnetAPrivatecRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: ToolSubnetA

  ToolSubnetBPrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable
      SubnetId:
        Ref: ToolSubnetB


Outputs:
  VPCId:
    Value: !Ref VpcIdParameter
    Export:
      Name: !Sub ${StackPrefix}-VPCId
    Description: AEM VPC Id

  PublishDispatcherELBSubnetA:
    Value:
      Ref: PublishDispatcherELBSubnetA
    Export:
      Name: !Sub ${StackPrefix}-PublishDispatcherELBSubnetA
    Description: The Publish Dispatcher ELB Subnet in Availability Zone A

  PublishDispatcherELBSubnetB:
    Value:
      Ref: PublishDispatcherELBSubnetB
    Export:
      Name: !Sub ${StackPrefix}-PublishDispatcherELBSubnetB
    Description: The Publish Dispatcher ELB Subnet in Availability Zone B

  PublishDispatcherSubnetA:
    Value:
      Ref: PublishDispatcherSubnetA
    Export:
      Name: !Sub ${StackPrefix}-PublishDispatcherSubnetA
    Description: The Publish Dispatcher Subnet in Availability Zone A

  PublishDispatcherSubnetB:
    Value:
      Ref: PublishDispatcherSubnetB
    Export:
      Name: !Sub ${StackPrefix}-PublishDispatcherSubnetB
    Description: The Publish Dispatcher Subnet in Availability Zone B

  PublishSubnetA:
    Value:
      Ref: PublishSubnetA
    Export:
      Name: !Sub ${StackPrefix}-PublishSubnetA
    Description: The Publish Subnet in Availability Zone A

  PublishSubnetB:
    Value:
      Ref: PublishSubnetB
    Export:
      Name: !Sub ${StackPrefix}-PublishSubnetB
    Description: The Publish Subnet in Availability Zone B

  AuthorSubnetA:
    Value:
      Ref: AuthorSubnetA
    Export:
      Name: !Sub ${StackPrefix}-AuthorSubnetA
    Description: The Author Subnet in Availability Zone A

  AuthorSubnetB:
    Value:
      Ref: AuthorSubnetB
    Export:
      Name: !Sub ${StackPrefix}-AuthorSubnetB
    Description: The Author Subnet in Availability Zone B

  AuthorDispatcherSubnetA:
    Value:
      Ref: AuthorDispatcherSubnetA
    Export:
      Name: !Sub ${StackPrefix}-AuthorDispatcherSubnetA
    Description: The Author Dispatcher Subnet in Availability Zone A

  AuthorDispatcherSubnetB:
    Value:
      Ref: AuthorDispatcherSubnetB
    Export:
      Name: !Sub ${StackPrefix}-AuthorDispatcherSubnetB
    Description: The Author Dispatcher Subnet in Availability Zone B

  ToolSubnetA:
    Value:
      Ref: ToolSubnetA
    Export:
      Name: !Sub ${StackPrefix}-ToolSubnetA
    Description: The Tool Subnet in Availability Zone A

  ToolSubnetB:
    Value:
      Ref: ToolSubnetB
    Export:
      Name: !Sub ${StackPrefix}-ToolSubnetB
    Description: The Tool Subnet in Availability Zone B

  PublicRouteTable:
    Value:
      Ref: PublicRouteTable
    Description: The Public Route Table for AEM Stack VPC
    Export:
      Name: !Sub ${StackPrefix}-PublicRouteTable

  PrivateRouteTable:
    Value:
      Ref: PrivateRouteTable
    Description: The Private Route Table for AEM Stack VPC
    Export:
      Name: !Sub ${StackPrefix}-PrivateRouteTable
