AWSTemplateFormatVersion: '2010-09-09'

Description: Overarching CF Template to Create Roles, Security Groups, and Messaging Resources for AEM Appp Stacks

Parameters:

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  NetworkStackPrefixParameter:
    Type: String
    Description: The AEM Stack Network Resources Stack Prefix

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  SecureShellInboundCidrIpParameter:
    Type: String
    Description: AEM Stack Secure Shell Inbound Cidr Ip

  PublishDispatcherELBSecurityGroupInboundCidrIpParameter:
    Type: String
    Description: AEM Publish Dispatcher ELB Security Group Inbound Cidr Ip

  AuthorDispatcherELBSecurityGroupInboundCidrIpParameter:
    Type: String
    Description: AEM Author Dispatcher ELB Security Group Inbound Cidr Ip

  PrivateSubnetInternetOutboundCidrIpParameter:
    Type: String
    Description: AEM Stack Private Subnet Internet Outbound Cidr Ip Destination


Resources:
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${ComputeStackPrefixParameter}/security-groups.yaml
      Parameters:
        ComputeStackPrefixParameter: !Ref ComputeStackPrefixParameter
        NetworkStackPrefixParameter: !Ref NetworkStackPrefixParameter
        SecureShellInboundCidrIpParameter: !Ref SecureShellInboundCidrIpParameter
        PublishDispatcherELBSecurityGroupInboundCidrIpParameter: !Ref PublishDispatcherELBSecurityGroupInboundCidrIpParameter
        AuthorDispatcherELBSecurityGroupInboundCidrIpParameter: !Ref AuthorDispatcherELBSecurityGroupInboundCidrIpParameter
        PrivateSubnetInternetOutboundCidrIpParameter: !Ref PrivateSubnetInternetOutboundCidrIpParameter

  RolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/${DataBucketNameParameter}/${ComputeStackPrefixParameter}/roles.yaml
      Parameters:
        ComputeStackPrefixParameter: !Ref ComputeStackPrefixParameter

Outputs:
  SecurityGroupStackName:
    Description: Security Group Stack Name
    Value: !Ref SecurityGroupStack
    Export:
      Name: !Sub ${ComputeStackPrefixParameter}-SecurityGroupStackName

  RolesStackName:
    Description: Roles Stack Name
    Value: !Ref RolesStack
    Export:
      Name: !Sub ${ComputeStackPrefixParameter}-RolesStackName
