---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Create security groups for the AEM Stack

Parameters:
  VpcIdParameter:
    Type: AWS::EC2::VPC::Id
    Default: vpc-ddc001b9
    Description: The VPC to create the AEM Stack Security Groups in.

Resources:
  PublishDispatcherELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: AEM Publish Dispatcher ELB Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: AEM Publish Dispatcher ELB Security Group
      VpcId: 
        Ref: VpcIdParameter
  
  PublishDispatcherSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: AEM Publish Dispatcher Security Group
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 10.0.20.0/24
      SecurityGroupIngress:
        - IpProtocol: "-1"
          CidrIp: 10.0.20.0/24
      Tags:
        - Key: Name
          Value: AEM Publish Dispatcher Security Group
      VpcId: 
        Ref: VpcIdParameter

  PublishDispatcherELBSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      DestinationSecurityGroupId:  
        Fn::GetAtt:
        - PublishDispatcherSecurityGroup
        - GroupId
      FromPort: '443'
      GroupId: 
        Fn::GetAtt:
        - PublishDispatcherELBSecurityGroup
        - GroupId
      IpProtocol: tcp
      ToPort: '443'
