---
- name: AEM Nat-Gateway CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Get AEM Stack VPC
      ec2_vpc_net_facts:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": "{{ ec2_vpc.tag_name }}"
      register: aem_stack_vpc
      tags:
      - create

    - name: Get Publish Dispatcher ELB Subnet A
      ec2_vpc_subnet_facts:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": "{{ network.publish_dispatcher_elb.subnet_a.tag_name }}"
          vpc-id: "{{ aem_stack_vpc.vpcs.0.id }}"
      register: publish_dispatcher_elb_subnet_a
      tags:
      - create

    - name: Create Nat Gateway Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ nat_gateway.stack_name }}"
        state: present
        region: "{{ aws.region }}"
        disable_rollback: true
        template: "../../../cloudformation/network/nat-gateway.yaml"
        template_parameters:
          Ec2NatGatewayElasticIpAllocationIdParameter: "{{ nat_gateway.elastic_ip_allocation_id }}"
          PublishDispatcherELBSubnetAParameter: "{{ publish_dispatcher_elb_subnet_a.subnets.0.id }}"
          NetworkStackNameParameter: "{{ network.stack_name }}"
      tags:
      - create

    - name: Delete Nat Gateway Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ nat_gateway.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      tags:
      - delete
