---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Create compute resources for the AEM Publish

Parameters:


Resources:

  AEMASGEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${StackName}-ASGEvent
      VisibilityTimeout: 30

  AEMASGEventQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          -
            Sid: SQS01
            Effect: Allow
            Principal:
              AWS:
                - "*"
            Action:
              - SQS:SendMessage
            Resource:
              - !GetAtt AEMASGEventQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref AEMASGEventTopic
      Queues:
        - !Ref AEMASGEventQueue

  AEMASGEventTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${StackName}-ASGEvent
      DisplayName: !Sub ${StackName}-AEM AutoScaling Event
      Subscription:
        -
          Endpoint: !GetAtt AEMASGEventQueue.Arn
          Protocol: sqs
