---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Create the Compute resources for the AEM Publish Dispatcher

Parameters:

  ComputeStackMonikerParameter:
    Type: String
    Default: default
    Description: The AEM Stack Compute Resources Stack Moniker

  SSLCertificateARNParameter:
    Type: String
    Default: arn:aws:iam::accountID:server-certificate/aem-stack-certificate
    Description: The ARN for SSL Certificate

  PublishDispatcherLoadBalancerHealthCheckTargetParameter:
    Type: String
    Default: HTTP:80/system/health
    Description: AEM Publish Dispatcher ELB Health Check Target

  PublishDispatcherSubnetAParameter:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-1f5ed07b
    Description: The Publish Dispatcher Subnet in Availability Zone A

  PublishDispatcherSubnetBParameter:
    Type: AWS::EC2::Subnet::Id
    Default: subnet-68d2641e
    Description: The Publish Dispatcher Subnet in Availability Zone B

  PublishDispatcherImageParameter:
    Type: AWS::EC2::Image::Id
    Default: ami-429ea621
    Description: The Publish Dispatcher Image Id

  PublishDispatcherInstanceTypeParameter:
    Type: String
    Default: t2.micro
    Description: The Publish Dispatcher Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Default: aem-default-stack-key-pair
    Description: The Compute Resources Key Pair Name

  PublishDispatcherASGAvailabilityZoneListParameter:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Default: ap-southeast-2a, ap-southeast-2b
    Description: The Publish Dispatcher Availability Zone List

#TODO: Combine this parameter with PublishDispatcherSubnetAParameter and PublishDispatcherSubnetBParameter
  PublishDispatcherASGSubnetListParameter:
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-1f5ed07b, subnet-68d2641e
    Description: The Publish Dispatcher Subnets

  PublishDispatcherASGMaxSizeParameter:
    Type: String
    Default: 2
    Description: The Publish Dispatcher Auto Scaling Group Maximum Size

  PublishDispatcherASGMinSizeParameter:
    Type: String
    Default: 2
    Description: The Publish Dispatcher Auto Scaling Group Minimum Size

  PublishDispatcherTagNameParameter:
    Type: String
    Default: AEM Publish Dispatcher
    Description: The Publish Dispatcher Name Tag

  ApplicationVersionParameter:
    Type: String
    Default: 1.0.0
    Description: The Application Version Number

  PublishDispatcherLoadBalancerTagNameParameter:
    Type: String
    Default: AEM Publish Dispatcher Load Balancer
    Description: The Publish Dispatcher Load Balancer Name Tag

  Route53RecordSetHostedZoneNameParameter:
    Type: String
    Default: aem-stack.com.
    Description: The Hosted Zone Name to be used by the AEM Stack

  PublishDispatcherRoute53RecordSetNameParamter:
    Type: String
    Default: default-publish-dispatcher.aem-stack.com.
    Description: The Publish Dispatcher Route53 CNAME Record Set Name

  RolesStackNameParameter:
    Type: String
    Default: aem-roles-stack
    Description: The AEM Roles Stack Name

  SecurityGroupsStackNameParameter:
    Type: String
    Default: aem-security-groups-stack
    Description: The AEM Security Groups Stack Name

  MessagingStackNameParameter:
    Type: String
    Default: aem-messaging-stack
    Description: The AEM Messaging Stack Name

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Default: sg-b74580d0
    Description: Inbound Bound from Bastion Host Security Group Id

Resources:

  PublishDispatcherLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 300
      CrossZone: true
      HealthCheck:
        Target:
          Ref: PublishDispatcherLoadBalancerHealthCheckTargetParameter
        HealthyThreshold: "2"
        UnhealthyThreshold: "2"
        Interval: "30"
        Timeout: "5"
      Listeners:
        - LoadBalancerPort: "80"
          InstancePort: "80"
          Protocol: HTTP
        - LoadBalancerPort: "443"
          Protocol: HTTPS
          InstancePort: "443"
          InstanceProtocol: HTTPS
          SSLCertificateId:
            Ref: SSLCertificateARNParameter
      Scheme: internet-facing
      SecurityGroups:
        - Fn::ImportValue: !Sub ${ComputeStackMonikerParameter}-${SecurityGroupsStackNameParameter}-PublishDispatcherELBSecurityGroup
      Subnets:
        - Ref: PublishDispatcherSubnetAParameter
        - Ref: PublishDispatcherSubnetBParameter
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${PublishDispatcherLoadBalancerTagNameParameter}
        - Key: Stack Moniker
          Value:
            Ref: ComputeStackMonikerParameter

  PublishDispatcherLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 10
            VolumeType: gp2
        - DeviceName: /dev/sdb
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 10
            VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: ${RolesStackNameParameter}-PublishDispatcherInstanceProfile
      ImageId:
        Ref: PublishDispatcherImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: PublishDispatcherInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
        - Fn::ImportValue: !Sub ${ComputeStackMonikerParameter}-${SecurityGroupsStackNameParameter}-PublishDispatcherSecurityGroup
        - Ref: InboundFromBastionHostSecurityGroupParameter
      # TODO: Setup UserData
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            -
              - "#!/bin/bash -x"
              - "\n"
              - "su - ec2-user -c \"echo TODO\""

#TODO: change to ELB Health Check Type once up and running
  PublishDispatcherAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Ref: PublishDispatcherASGAvailabilityZoneListParameter
      HealthCheckGracePeriod: 900
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: PublishDispatcherLaunchConfiguration
      LoadBalancerNames:
        - Ref: PublishDispatcherLoadBalancer
      MaxSize:
        Ref: PublishDispatcherASGMaxSizeParameter
      MinSize:
        Ref: PublishDispatcherASGMinSizeParameter
      NotificationConfigurations:
        - NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
          TopicARN:
            Fn::ImportValue: !Sub ${ComputeStackMonikerParameter}-${MessagingStackNameParameter}-AEMASGEventTopic
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${PublishDispatcherTagNameParameter} (${ComputeStackMonikerParameter})
          PropagateAtLaunch: true
        - Key: Stack Moniker
          Value:
            Ref: ComputeStackMonikerParameter
          PropagateAtLaunch: true
        - Key: Component
          Value: aem-publish-dispatcher
          PropagateAtLaunch: true
        - Key: Application Version
          Value:
            Ref: ApplicationVersionParameter
          PropagateAtLaunch: true
      VPCZoneIdentifier:
        Ref: PublishDispatcherASGSubnetListParameter

  PublishDispatcherRoute53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName:
        Ref: Route53RecordSetHostedZoneNameParameter
      Name:
        Ref: PublishDispatcherRoute53RecordSetNameParamter
      ResourceRecords:
        - Fn::GetAtt: [PublishDispatcherLoadBalancer, DNSName]
      TTL: 300
      Type: CNAME

Outputs:

  PublishDispatcherLoadBalancer:
    Value:
      Ref: PublishDispatcherLoadBalancer
    Description: The Publish Dispatcher Load Balancer

  PublishDispatcherLaunchConfiguration:
    Value:
      Ref: PublishDispatcherLaunchConfiguration
    Description: The Publish Dispatcher Launch Configuration

  PublishDispatcherAutoScalingGroup:
    Value:
      Ref: PublishDispatcherAutoScalingGroup
    Description: The Publish Dispatcher Auto Scaling Group

  PublishDispatcherRoute53RecordSet:
    Value:
      Ref: PublishDispatcherRoute53RecordSet
    Description: The Publish Dispatcher Route53 CNAME Record
