---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Create the Compute resources for the AEM Publish

Parameters:

  ComputeStackPrefixParameter:
    Type: String
    Default: default
    Description: The AEM Stack Compute Resources Stack Prefix

  PublishImageParameter:
    Type: AWS::EC2::Image::Id
    Default: ami-3794ac54
    Description: The Publish Image Id

  PublishInstanceTypeParameter:
    Type: String
    Default: m3.large
    Description: The Publish Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Default: aem-default-stack-key-pair
    Description: The Compute Resources Key Pair Name

  PublishASGAvailabilityZoneListParameter:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Default: ap-southeast-2a, ap-southeast-2b
    Description: The Publish Availability Zone List

  PublishASGSubnetListParameter:
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-27b53c43, subnet-afec5dd9
    Description: The Publish Subnets

  PublishASGMaxSizeParameter:
    Type: String
    Default: 2
    Description: The Publish Auto Scaling Group Maximum Size

  PublishASGMinSizeParameter:
    Type: String
    Default: 2
    Description: The Publish Auto Scaling Group Minimum Size

  PublishTagNameParameter:
    Type: String
    Default: AEM Publish
    Description: The Publish Name Tag

  ApplicationVersionParameter:
    Type: String
    Default: 1.0.0
    Description: The Application Version Number

  RolesStackNameParameter:
    Type: String
    Default: aem-roles-stack
    Description: The AEM Roles Stack Name

  SecurityGroupsStackNameParameter:
    Type: String
    Default: aem-security-groups-stack
    Description: The AEM Security Groups Stack Name

  MessagingStackNameParameter:
    Type: String
    Default: aem-messaging-stack
    Description: The AEM Messaging Stack Name

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Default: sg-b74580d0
    Description: Inbound Bound from Bastion Host Security Group Id

Resources:

  PublishLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 10
            VolumeType: gp2
        - DeviceName: /dev/sdb
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 10
            VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: ${RolesStackNameParameter}-PublishInstanceProfile
      ImageId:
        Ref: PublishImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: PublishInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
        - Fn::ImportValue: !Sub ${ComputeStackPrefixParameter}-${SecurityGroupsStackNameParameter}-PublishSecurityGroup
        - Ref: InboundFromBastionHostSecurityGroupParameter
      # TODO: Setup UserData
      UserData:
        Fn::Base64:
          Fn::Join:
            - ""
            -
              - "#!/bin/bash -x"
              - "\n"
              - "su - ec2-user -c \"echo TODO\""

  PublishAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Ref: PublishASGAvailabilityZoneListParameter
      HealthCheckGracePeriod: 900
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: PublishLaunchConfiguration
      MaxSize:
        Ref: PublishASGMaxSizeParameter
      MinSize:
        Ref: PublishASGMinSizeParameter
      NotificationConfigurations:
        - NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
          TopicARN:
            Fn::ImportValue: !Sub ${ComputeStackPrefixParameter}-${MessagingStackNameParameter}-AEMASGEventTopic
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${PublishTagNameParameter} (${ComputeStackPrefixParameter})
          PropagateAtLaunch: true
        - Key: Stack Prefix
          Value:
            Ref: ComputeStackPrefixParameter
          PropagateAtLaunch: true
        - Key: Component
          Value: aem-publish
          PropagateAtLaunch: true
        - Key: Application Version
          Value:
            Ref: ApplicationVersionParameter
          PropagateAtLaunch: true
      VPCZoneIdentifier:
        Ref: PublishASGSubnetListParameter


Outputs:

  PublishLaunchConfiguration:
    Value:
      Ref: PublishLaunchConfiguration
    Description: The Publish Launch Configuration

  PublishAutoScalingGroup:
    Value:
      Ref: PublishAutoScalingGroup
    Description: The Publish Auto Scaling Group
