---
- name: Author Publish Dispatcher Prerequisites CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create Author Publish Dispatcher Prerequisites Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ security_groups.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../../../../cloudformation/apps/author-publish-dispatcher/prerequisites.yaml"
        template_parameters:
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          VPCId: "{{ aem_vpc.id }}"
      tags:
      - create

    - name: Check if a Stack Exists
      command: >
            aws cloudformation describe-stacks --stack-name "{{ stack_prefix }}-{{ security_groups.stack_name }}"
                --query 'Stacks[].StackName' --region "{{ aws.region }}"
      ignore_errors: True
      register: stack_query
      tags:
        - delete

    - name: Report Stack Problem
      debug:
        msg: Stack "{{ stack_prefix }}-{{ security_groups.stack_name }}" does not exist or some other errors occured
      when:
        "stack_query.rc != 0"
      tags:
        - delete

    - name: Delete AEM Security Groups Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ security_groups.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      when:
        "stack_query.rc == 0"
      tags:
      - delete
