---
- name: AEM Author Dispatcher CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Get AEM Stack VPC
      ec2_vpc_net_facts:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": "{{ ec2_vpc.tag_name }}"
      register: aem_stack_vpc
      tags:
      - create

    - name: Get Dispatcher AMI
      ec2_ami_find:
        ami_tags:
          component: dispatcher
          version: "{{ dispatcher.ami_version }}"
        sort: creationDate
        sort_order: descending
        sort_end: 1
      register: dispatcher_ami
      tags:
      - create

    - name: Get Author Dispatcher ELB Security Group
      ec2_group_facts:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": AEM Author Dispatcher ELB Security Group
          vpc-id: "{{ aem_stack_vpc.vpcs.0.id }}"
      register: author_dispatcher_elb_security_group
      tags:
      - create

    - name: Get Author Dispatcher Subnet A
      ec2_vpc_subnet_facts:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": AEM Author Dispatcher Subnet A
          vpc-id: "{{ aem_stack_vpc.vpcs.0.id }}"
      register: author_dispatcher_subnet_a
      tags:
      - create

    - name: Get Author Dispatcher Subnet B
      ec2_vpc_subnet_facts:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": AEM Author Dispatcher Subnet B
          vpc-id: "{{ aem_stack_vpc.vpcs.0.id }}"
      register: author_dispatcher_subnet_b
      tags:
      - create

    - name: Get Author Dispatcher Security Group
      ec2_group_facts:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": AEM Author Dispatcher Security Group
          vpc-id: "{{ aem_stack_vpc.vpcs.0.id }}"
      register: author_dispatcher_security_group
      tags:
      - create

    - name: Create AEM Author Dispatcher Stack
      cloudformation:
        stack_name: "{{ author_dispatcher.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../templates/compute/author-dispatcher.yaml"
        template_parameters:
          VpcIdParameter: "{{ aem_stack_vpc.vpcs.0.id }}"
      tags:
      - create

    - name: Delete AEM Author Dispatcher Stack
      cloudformation:
        stack_name: "{{ author_dispatcher.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      tags:
      - delete

