---
- name: AEM Publish CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:

    - name: Get AEM Stack VPC
      ec2_vpc_net_facts:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": "{{ ec2_vpc.tag_name }}"
      register: aem_stack_vpc
      tags:
      - create

    - name: Get Publish Subnet A
      ec2_vpc_subnet_facts:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": "{{ network.publish.subnet_a.tag_name }}"
          vpc-id: "{{ aem_stack_vpc.vpcs.0.id }}"
      register: publish_subnet_a
      tags:
      - create

    - name: Get Publish Subnet B
      ec2_vpc_subnet_facts:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": "{{ network.publish.subnet_b.tag_name }}"
          vpc-id: "{{ aem_stack_vpc.vpcs.0.id }}"
      register: publish_subnet_b
      tags:
      - create

    - name: Get Publish Security Group
      ec2_group_facts:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": "{{ security_groups.publish.tag_name }}"
          "tag:Stack Moniker": "{{ compute.stack_moniker }}"
          vpc-id: "{{ aem_stack_vpc.vpcs.0.id }}"
      register: publish_security_group
      tags:
      - create

    - name: Get Publish AMI
      ec2_ami_find:
        region: "{{ aws.region }}"
        ami_tags:
          component: publish
          version: "{{ publish.ami_version }}"
        sort: creationDate
        sort_order: descending
        sort_end: 1
      register: publish_ami
      tags:
      - create

#TODO: the ASG SNS Topic will be shared across ASG. need to move to messaging yaml.
#TODO: need a way to retrieve the topic
    - name: Create aem stack ASG SNS topic
      sns_topic:
        region: "{{ aws.region }}"
        name: "{{ compute.stack_moniker }}-{{ messaging.asg_sns_topic_name }}"
      register: asg_sns_topic
      tags:
      - create

    - name: Create AEM Publish Stack
      cloudformation:
        stack_name: "{{ compute.stack_moniker }}-{{ publish.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../cloudformation/specific/publish.yaml"
        template_parameters:
          ComputeStackMonikerParameter: "{{ compute.stack_moniker }}"
          PublishImageParameter: "{{ publish_ami.results[0].ami_id }}"
          PublishInstanceTypeParameter: "{{ publish.instance_type }}"
          ComputeKeyPairNameParameter: "{{ compute.key_pair_name }}"
          PublishSecurityGroupParameter: "{{ publish_security_group.security_groups.0.group_id }}"
          PublishASGAvailabilityZoneListParameter: "{{ aws.availability_zone_a }}, {{ aws.availability_zone_b }}"
          PublishASGSubnetListParameter: "{{ publish_subnet_a.subnets.0.id }}, {{ publish_subnet_b.subnets.0.id }}"
          PublishASGMaxSizeParameter: "{{ publish.max_size }}"
          PublishASGMinSizeParameter: "{{ publish.min_size }}"
          AEMAutoScalingGroupSNSTopicParameter: "{{ asg_sns_topic.sns_arn }}"
          PublishTagNameParameter: "{{ publish.tag_name }}"
          ApplicationVersionParameter: "{{ compute.application_version }}"
          PublishInstanceProfileParameter: "{{ publish.iam_instance_profile }}"
      tags:
      - create

    - name: Delete AEM Publish Stack
      cloudformation:
        stack_name: "{{ compute.stack_moniker }}-{{ publish.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      tags:
      - delete
