---
- name: AEM Security Groups CloudFormation Stack
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Get AEM Stack VPC
      ec2_vpc_net_facts:
        region: "{{ aws.region }}"
        filters:
          "tag:Name": "{{ ec2_vpc.tag_name }}"
      register: aem_stack_vpc
      tags:
      - create

    - name: Create AEM Security Groups Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ security_groups.stack_name }}"
        region: "{{ aws.region }}"
        state: present
        disable_rollback: true
        template: "../cloudformation/apps/security-groups.yaml"
        template_parameters:
          VpcIdParameter: "{{ aem_stack_vpc.vpcs.0.id }}"
          ComputeStackPrefixParameter: "{{ stack_prefix }}"
          SecureShellInboundCidrIpParameter: "{{ security_groups.secure_shell.inbound_cidr_ip }}"
          PublishDispatcherELBSecurityGroupInboundCidrIpParameter: "{{ security_groups.publish_dispatcher_elb.inbound_cidr_ip }}"
          PublishDispatcherELBSecurityGroupTagNameParameter: "{{ security_groups.publish_dispatcher_elb.tag_name }}"
          PublishDispatcherSecurityGroupTagNameParameter: "{{ security_groups.publish_dispatcher.tag_name }}"
          AuthorSecurityGroupTagNameParameter: "{{ security_groups.author.tag_name }}"
          AuthorELBSecurityGroupTagNameParameter: "{{ security_groups.author_elb.tag_name }}"
          AuthorDispatcherSecurityGroupTagNameParameter: "{{ security_groups.author_dispatcher.tag_name }}"
          AuthorDispatcherELBSecurityGroupTagNameParameter: "{{ security_groups.author_dispatcher_elb.tag_name }}"
          AuthorDispatcherELBSecurityGroupInboundCidrIpParameter: "{{ security_groups.author_dispatcher_elb.inbound_cidr_ip }}"
          OrchestratorSecurityGroupTagNameParameter: "{{ security_groups.orchestrator.tag_name }}"
          ChaosMonkeySecurityGroupTagNameParameter: "{{ security_groups.chaos_monkey.tag_name }}"
          PrivateSubnetInternetOutboundCidrIpParameter: "{{ security_groups.private_subnet_internet_outbound_cidr_ip }}"
      tags:
      - create

    - name: Delete AEM Security Groups Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}-{{ security_groups.stack_name }}"
        region: "{{ aws.region }}"
        state: absent
      tags:
      - delete
